In [19]:
import numpy as np
data = np.loadtxt('datasets/synth.tr')

In [31]:
# return all features except last column
train_data = data[:, :-1]
train_data

array([[ 0.05100797,  0.16086164],
       [-0.74807425,  0.08904024],
       [-0.77293371,  0.26317168],
       [ 0.2183736 ,  0.12706142],
       [ 0.37268336,  0.496562  ],
       [-0.62931544,  0.63202159],
       [-0.43307167,  0.14479166],
       [-0.8415197 , -0.19131316],
       [ 0.47525648,  0.22483671],
       [ 0.32082976,  0.32721288],
       [ 0.32061253,  0.33407547],
       [-0.89077472,  0.41168783],
       [ 0.17850119,  0.44691359],
       [ 0.31558002,  0.38853383],
       [ 0.55777224,  0.47272748],
       [ 0.03191877,  0.01222964],
       [ 0.25090585,  0.30716705],
       [ 0.23571547,  0.22493837],
       [-0.07236203,  0.33376524],
       [ 0.50440241,  0.08054579],
       [-0.63223351,  0.44552458],
       [-0.76784656,  0.23614689],
       [-0.70017557,  0.21038848],
       [-0.64713491,  0.15921366],
       [-0.76739248,  0.09259038],
       [-0.51788734,  0.03288107],
       [ 0.17516644,  0.34534871],
       [-0.6803119 ,  0.47612156],
       [ 0.01595199,

In [34]:
train_data[0, :]

array([0.05100797, 0.16086164])

In [21]:
train_label = data[:, -1].astype(int)

In [23]:
train_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
# number of unique class
classn = np.unique(label)
classn

array([0, 1])

In [29]:
# num of rows
np.shape(train_data)


(250, 2)

In [26]:
# num of columns
nc = np.size(train_data, 1)
nc

2